import os
from google import genai
from google.genai import types
from docx import Document
from datetime import datetime

# --- Configuration ---
INSTRUCTION_FILE = "instructions_threat_hunting_new.docx"  # The file containing your AI instructions
OUTPUT_FILE = "threat_hunting_queries.md"
TARGET_PLATFORMS = ["SPL", "KQL", "AQL", "UDM"]


# --- 1. File Reading Logic ---
def read_file_content(filepath):
    """Reads content from a specified file (.txt or .docx based on extension)."""
    if filepath.endswith('.docx'):
        try:
            document = Document(filepath)
            full_text = [para.text for para in document.paragraphs]
            return '\n'.join(full_text)
        except FileNotFoundError:
            print(f"ERROR: DOCX file not found at {filepath}")
            return None
        except Exception as e:
            print(f"ERROR reading DOCX file {filepath}: {e}")
            return None
    else:
        try:
            with open(filepath, 'r', encoding='utf-8') as f:
                return f.read()
        except FileNotFoundError:
            print(f"ERROR: File not found at {filepath}")
            return None
        except Exception as e:
            print(f"ERROR reading file {filepath}: {e}")
            return None


# --- 2. Write Results to Markdown ---
def write_results_to_file(results):
    """Writes the combined results to a Markdown file."""
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    content = f"# 🕵️ Threat Hunting Queries\n"
    content += f"**Date Generated:** {timestamp}\n\n"
    content += "---\n\n"
    content += "This document contains automated threat hunting queries generated by the Gemini API.\n\n"
    content += "---\n\n"

    for platform, query_text in results.items():
        content += f"## 💻 {platform} Queries\n\n"
        content += query_text
        content += "\n\n---\n\n"

    try:
        with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:
            f.write(content)
        print(f"\n✅ Success! All queries saved to: {OUTPUT_FILE}")
    except Exception as e:
        print(f"\n❌ Error writing to file: {e}")


# --- 3. Call the Gemini API ---
def generate_queries(report_text, platform, raw_instructions):
    """Calls Gemini API using instructions loaded from the .docx file."""

    if not os.getenv("GEMINI_API_KEY"):
        raise ValueError("GEMINI_API_KEY environment variable not set.")

    client = genai.Client()

    # Mapping codes to full names for dynamic injection into instructions
    platform_map = {
        "KQL": ("Microsoft Azure Sentinel", "Kusto Query Language (KQL)"),
        "AQL": ("IBM QRadar", "AQL"),
        "UDM": ("Google SecOps (Chronicle)", "UDM (Unified Data Model)"),
        "SPL": ("Splunk", "Splunk Search Processing Language (SPL)"),
    }

    if platform not in platform_map:
        raise ValueError(f"Unsupported platform: {platform}")

    siem_name, query_lang = platform_map[platform]

    # Inject the specific platform details into the instruction template
    try:
        system_instruction = raw_instructions.format(
            siem_name=siem_name,
            query_lang=query_lang
        )
    except KeyError as e:
        print(f"⚠️ Warning: Instruction file is missing placeholder {e}. Using raw text.")
        system_instruction = raw_instructions

    full_prompt = (
        "Threat Report to Analyze:\n"
        "============================\n"
        f"{report_text}\n"
        "============================\n\n"
        f"Please generate the queries for {siem_name} now."
    )

    print(f"-> Generating queries for {siem_name}...")

    try:
        response = client.models.generate_content(
            model='gemini-2.5-flash',
            contents=full_prompt,
            config=types.GenerateContentConfig(
                system_instruction=system_instruction
            )
        )
        return response.text
    except Exception as e:
        return f"Gemini API Error: {e}"


# --- 5. Main Execution ---
def threat_hunting_queries_recommendation(plain_text_content):

    instruction_template = read_file_content(INSTRUCTION_FILE)

    if plain_text_content and instruction_template:
        all_results = {}

        for platform in TARGET_PLATFORMS:
            generated_queries = generate_queries(plain_text_content, platform, instruction_template)
            all_results[platform] = generated_queries

        write_results_to_file(all_results)
    else:
        print("❌ Script aborted: Required input files could not be read.")